# === BUILDER STAGE ===
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source code and run the build (Requires output: "standalone" in next.config.js)
COPY . .
RUN npm run build

# === RUNNER STAGE ===
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Consolidate user/group creation
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Set environment variables
ENV PORT=3000

# Copy necessary files from the builder stage
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user for security
USER nextjs

EXPOSE 3000

# FINAL FIX: Use the 'next start' command to run the standalone build.
# The 'server.js' file is automatically generated by Next.js in the standalone output directory.
CMD ["npm", "start"]