version: 0.2
env:
  variables:
    AWS_REGION: us-east-1
  
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y jq curl

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo Build started on $(date)
      
      - |
        docker build \
        --build-arg OPENAI_API_KEY=$OPENAI_API_KEY \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
        --build-arg NEXT_PUBLIC_AUTH_GITHUB=$NEXT_PUBLIC_AUTH_GITHUB \
        -t $ECR_REPO_URI$CODEBUILD_RESOLVED_COMMIT_ID .
      
      - docker tag $ECR_REPO_URI$CODEBUILD_RESOLVED_COMMIT_ID $ECR_REPO_URI:latest


  post_build:
    commands:
      - echo Pushing the Docker images to ECR
      - docker push $ECR_REPO_URI$CODEBUILD_RESOLVED_COMMIT_ID
      - docker push $ECR_REPO_URI:latest
      
      - echo Deploying App Runner service with new image
      - aws apprunner start-deployment --service-arn $APP_RUNNER_SERVICE_ARN

      - echo Retrieving GitHub PAT from Secrets Manager for tagging
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id $GITHUB_PAT_SECRET_ARN --query SecretString --output text)
      - export COMMIT_SHA=$CODEBUILD_RESOLVED_COMMIT_ID
      - export GIT_TAG="deployed-dev"
      
      - echo Auto-tagging commit $COMMIT_SHA with $GIT_TAG on $GITHUB_OWNER/$GITHUB_REPO
      - |
        curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/git/refs/tags/$GIT_TAG"
      
      - |
        curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"ref": "refs/tags/'$GIT_TAG'", "sha": "'$COMMIT_SHA'"}' \
          "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/git/refs"
      
      - echo Auto-tagging complete.